In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [2]:
data = pd.read_csv("zoo.csv")

In [3]:
data

1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6  \
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0   
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1   
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...   
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1   
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0   
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0   
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0   

    1.7  
0     1  
1     4  
2     1  
3     1  
4     1  
..  ...  
95    1  
96    6  
97    1  
98    7  
99    2  

[100 rows x 17 columns]

In [4]:
y = data["1.7"]
y

0     1
1     4
2     1
3     1
4     1
     ..
95    1
96    6
97    1
98    7
99    2
Name: 1.7, Length: 100, dtype: int64

In [5]:
x = data.drop(["1.7"],axis=1)

In [6]:
x

1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0

[100 rows x 16 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [8]:
# make the model of the classfier
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [9]:
# now we need to have y_pred
y_pred = classifier.predict(x_test)
y_pred

array([6, 2, 1, 1, 2, 1, 7, 4, 1, 5, 1, 7, 2, 7, 1, 1, 1, 2, 7, 4],
      dtype=int64)

In [10]:
# now we need to check for the performance
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [11]:
print("accuracy is : ",accuracy_score(y_test,y_pred))

accuracy is :  0.95


In [12]:
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[8 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 4]]


In [13]:
print("Classification Report:\n",classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         4
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         2
           5       0.00      0.00      0.00         0
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         4

    accuracy                           0.95        20
   macro avg       0.71      0.71      0.71        20
weighted avg       0.95      0.95      0.95        20



C:\Users\suraj\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\suraj\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\suraj\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifie